# Site settings
title: "Model Context Protocol Security"
description: "A Cloud Security Alliance Community Project - Secure Autonomy: Hardening Model-Context-Protocol Servers & Agents"
url: "https://modelcontextprotocol-security.io"
baseurl: ""

# Organization info
organization: "Cloud Security Alliance"
organization_url: "https://cloudsecurityalliance.org"
github_username: "ModelContextProtocol-Security"

# Just the Docs theme
remote_theme: just-the-docs/just-the-docs

# Color scheme (CSA inspired)
color_scheme: csa

# Logo
logo: "/assets/images/mcp-security-logo.svg"

# Search
search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Navigation
nav_sort: case_insensitive
nav_external_links:
  - title: "GitHub Discussions"
    url: "https://github.com/orgs/ModelContextProtocol-Security/discussions"
    hide_icon: false
  - title: "Cloud Security Alliance"
    url: "https://cloudsecurityalliance.org"
    hide_icon: false

# Aux links for the upper right navigation
aux_links:
  "GitHub Repository":
    - "https://github.com/ModelContextProtocol-Security/modelcontextprotocol-security.io"
  "Join Discussion":
    - "https://github.com/orgs/ModelContextProtocol-Security/discussions"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Footer
footer_content: "This project is sponsored by the <a href=\"https://cloudsecurityalliance.org\">Cloud Security Alliance</a> and maintained by the Model Context Protocol Security Working Group."

# Google Analytics (optional)
# ga_tracking: UA-XXXXXXXX-X

# Heading anchors
heading_anchors: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - node_modules/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Sass settings
sass:
  sass_dir: _sass
  style: compressed

# Compression
compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false

# Collections (for organizing content)
collections:
  guides:
    output: true
    permalink: /:collection/:name/
  patterns:
    output: true
    permalink: /:collection/:name/
  tools:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: "why"
    values:
      parent: "Why MCP Security?"
      nav_order: 1
  - scope:
      path: "hardening"
    values:
      parent: "Hardening Guide"
      nav_order: 2
  - scope:
      path: "operations"
    values:
      parent: "Operations Guide"
      nav_order: 3
  - scope:
      path: "patterns"
    values:
      parent: "Reference Patterns"
      nav_order: 4
  - scope:
      path: "audit"
    values:
      parent: "Audit Tools"
      nav_order: 5
  - scope:
      path: "tools"
    values:
      parent: "Tools & Scripts"
      nav_order: 6
  - scope:
      path: "vulnerability-db"
    values:
      parent: "Vulnerability Database"
      nav_order: 7
  - scope:
      path: "community"
    values:
      parent: "Community"
      nav_order: 8
  - scope:
      path: "blog"
    values:
      parent: "Blog"
      nav_order: 9
  - scope:
      path: "events"
    values:
      parent: "Events"
      nav_order: 10
